accountsApp/urls.py
from django.conf.urls import url
from .views import LoginView, RegisterStudentView, RegisterProfessorView, LogoutView

app_name='accountsApp'

urlpatterns = [
	url(r'^$', LoginView.as_view(), name='login'),
	url(r'^logout/$', LogoutView.as_view(), name='logout'),
	url(r'^reg/s/$', RegisterStudentView.as_view(), name='regStudent'),
	url(r'^reg/p/$', RegisterProfessorView.as_view(), name='regProf'),
]

coursesApp/urls.py
from django.conf.urls import url
from .views import CoursesViewVersion2, CourseView

app_name='coursesApp'

urlpatterns = [
	url(r'^$', CoursesViewVersion2.as_view(), name='courses'),
	url(r'^(?P<course_id>[0-9]+)/$', CourseView.as_view(), name='view_course'),
]

husite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^news/', include('newsApp.urls')),
	url(r'^professors/', include('professorsApp.urls')),
	url(r'^events/', include('eventsApp.urls')),
	url(r'^', include('accountsApp.urls')),
	url(r'^sessions/', include('sessionManagerApp.urls')),
	url(r'^profile/', include('profileApp.urls')),
    url(r'^courses/', include('coursesApp.urls')),
    url(r'^departments/', include('departmentsApp.urls')),
    url(r'^assignments/', include('quizesApp.urls')),
    url(r'^lectures/', include('lecturesApp.urls')),
    url(r'exam/', include('onlineExamsApp.urls')),
    url(r'dashboard/', include('dashboard.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profileApp/urls.py
from django.conf.urls import url

from .views import ProfileHomeView, ScheduleView, OldSemestersView, SessionsView

app_name = 'profileApp'

urlpatterns = [
	url(r'^$', ProfileHomeView.as_view(), name='profile'),
	url(r'^schedule/$', ScheduleView.as_view(), name='schedule'),
	url(r'^semesters/$', OldSemestersView.as_view(), name='semesters'),
	url(r'^sessions/$', SessionsView.as_view(), name='sessions'),
]

quizesApp/urls.py
from django.conf.urls import url
from .views import QuizesView, DeleteQuizView, QuizResultsView


app_name='quizesApp'

urlpatterns = [
	url(r'^(?P<session_id>[0-9]+)/$', QuizesView.as_view(), name='view'),
	url(r'^delete/(?P<quiz_id>[0-9]+)/$', DeleteQuizView.as_view(), name='delete'),
	url(r'^view/(?P<quiz_id>[0-9]+)/$', QuizResultsView.as_view(), name='results'),
]

sessionManagerApp/urls.py
from django.conf.urls import url
from .views import ManageSessionsView, ViewSessionsView, DropSessionView, DropSession, ChatView, CloseChatView

app_name='sessionManagerApp'

urlpatterns = [
	url(r'^manage/$', ManageSessionsView.as_view(), name='manage'),
	url(r'^view/(?P<session_id>[0-9]+)/$', ViewSessionsView.as_view(), name='view'),
	url(r'^drop/view/(?P<session_id>[0-9]+)/$', DropSessionView.as_view(), name='drop_view'),
	url(r'^drop/(?P<session_id>[0-9]+)/$', DropSession.as_view(), name='drop'),
	url(r'^chat/(?P<session_id>[0-9]+?)/$', ChatView.as_view(), name='chat'),
	url(r'^chat/close/(?P<session_id>[0-9]+?)/$', CloseChatView.as_view(), name='close_chat')
]

sessionManagerApp/models.py
from django.db import models
from professorsApp.models import Professor
from coursesApp.models import Course
from django.contrib.auth.models import User
from datetime import timedelta, datetime, date

class Session(models.Model):
	DAYS_OF_WEEK_CHOICES = (
		('1', 'Saturday'),
		('2', 'Sunday'),
		('3', 'Monday'),
		('4', 'Tuesday'),
		('5', 'Wednesday'),
		('6', 'Thursday'),
		('7', 'Friday'),
	)
	professor = models.ForeignKey(Professor, null=True, blank=True, on_delete=models.CASCADE)
	course = models.ForeignKey(Course, on_delete=models.CASCADE)
	startTime = models.TimeField()
	endTime = models.TimeField(editable=False)
	dayOfWeek = models.CharField(max_length=1, choices=DAYS_OF_WEEK_CHOICES, default='1')
	location = models.CharField(max_length=15, default='P512')
	chatActive = models.BooleanField(default=False, blank=False, null=False)

	def save(self, *args, **kwargs):
		self.endTime = (datetime.combine(date(1, 1, 1), self.startTime) + timedelta(hours = self.course.duration.hour, minutes=self.course.duration.minute)).time()
		super(Session, self).save(*args, **kwargs)
		
	def __str__(self):
		if self.professor:
			return self.professor.name + " - " + self.course.name + " - " + str(self.get_dayOfWeek_display()) + " - "  + str(self.startTime) + " -> " + str(self.endTime)
		return "undefined" + " - " + self.course.name + " - " + str(self.get_dayOfWeek_display()) + " - "  + str(self.startTime) + " -> " + str(self.endTime)


class ChatFullName(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, null=False)
	name = models.CharField(max_length=20, blank=False, null=False)
	session = models.ForeignKey(Session, on_delete=models.CASCADE)

	def __str__(self):
		return self.name

sessionManagerApp/views.py
from datetime import date, datetime, timedelta

from django.conf import settings
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View

from coursesApp.models import Course
from departmentsApp.models import Department, Group
from professorsApp.models import Professor
from settingsApp.models import Setting
from studentsApp.models import StudentInfo

from .models import Session

login_redirect_url = getattr(settings, 'LOGIN_URL', 'accountsApp:login')
view_sessions_redirect_url = 'sessionManagerApp:viewSessions'

# SHOULD PROBABLY MAKE THE THREE FUNCTIONS INTO ONE, TO AVOID LOTS OF DB USAGE,
# OR WE SHOULD CACHE THE QUERUES GLOBALLY.

def SessionSameGroup(s, u):
	return s.course.group == get_object_or_404(StudentInfo, user=u).group

def PrerequistiesDone(s, u):
	c_list = []
	for semester in StudentInfo.objects.get(user=u).usersemester_set.all():
		for c_c in semester.completedcourse_set.all():
			c_list.append(c_c.course)
	return set(s.course.prequels.all()).issubset(c_list)
	
def SessionCompleted(s, u):
	for semester in StudentInfo.objects.get(user=u).usersemester_set.all():	
		for c_course in semester.completedcourse_set.all():
			if s.course == c_course.course:
				return True
	return False
	
def SessionOnGoing(s, u):
	if s in StudentInfo.objects.get(user=u).sessions.all():
		return True
	return False
	
def DoDataForEveryUser():
	for u in User.objects.all():
		us = UserInfo(user=u)
		us.save()

class ManageSessionsView(View):
	def post(self, request):
		if not request.user.is_authenticated:
			return redirect(login_redirect_url)
		if not Setting.objects.first().canChangeSessions:
			return render(request, 'error.html', {})
		
		group = request.POST.get("selectedDepartment")

		if group:
			info = StudentInfo.objects.get(user=request.user)
			info.group = get_object_or_404(Group, name=group)
			info.save()
			return redirect('sessionManagerApp:manage')

		selectedSessions = [Session.objects.get(id=x) for x in request.POST.getlist("selectedCourses")]
		errorList = []
		
		# Check if there's any confliction between courses timings.
		conflictError = False
		course1Conflict = ""
		course2Conflict = ""
		for x in selectedSessions:
			if conflictError:
				break
				
			for y in selectedSessions:
				if x != y and y.startTime >= x.startTime and y.startTime < x.endTime and x.dayOfWeek == y.dayOfWeek:
					conflictError = True
					course1Conflict = x.course.name
					course2Conflict = y.course.name
					break
		
		# Check if there's any errors with hours / week 
		selectedHours = sum([x.course.duration.hour for x in selectedSessions])
		minHours = Setting.objects.all()[0].minHoursWeek
		maxHours = Setting.objects.all()[0].maxHoursWeek
		hoursError =  selectedHours < minHours or selectedHours > maxHours
		
		# Check for duplicate courses
		duplicateError = False
		duplicateName = ""
		coursesList = {}
		for session in selectedSessions:
			if session.course.name in coursesList:
				duplicateError = True
				duplicateName = session.course.name
				break
			else:
				coursesList[session.course.name] = 1

		# Add errors
		if conflictError:
			errorList.append(("There's confliction between the courses you choosen ({0} - {1}). Consider choosing different course times.").format(course1Conflict, course2Conflict))
		if hoursError:
			errorList.append(("You cannot save because your weekly hours doesn't meet the requirements: Minimum hours/week = {0}, Maximmum hours/week = {1}.").format(minHours, maxHours))
		if duplicateError:
			errorList.append(("There's duplicate courses you've selected with different locations/times ({0}), you're only allowed to register a course once.").format(duplicateName))
		if len([s for s in selectedSessions if not PrerequistiesDone(s, request.user)]) > 0:
			errorList.append("You shouldn't be seeing this! It appears like you've selected some courses without completing their prerequisties.")
		if len([s for s in selectedSessions if SessionCompleted(s, request.user)]) > 0:
			errorList.append("You shouldn't be seeing this! It appears you've selected a completed course already.")

		# Show errors, if any.
		if len(errorList) > 0:
			context = {
				'allSessions': [x for x in Session.objects.all() if not SessionCompleted(x, request.user) and PrerequistiesDone(x, request.user) and x not in selectedSessions],
				'userSessions': selectedSessions,
				'allCourses': Course.objects.all(),
				'userTotalHours': selectedHours,
				'minHoursWeek': Setting.objects.all()[0].minHoursWeek,
				'maxHoursWeek': Setting.objects.all()[0].maxHoursWeek,
				'errorList': errorList,
			}
			
			return render(request, 'sessionManagerApp/manage.html', context)
		else:
			userObj = StudentInfo.objects.get(user=request.user)
			userObj.sessions.clear()
			
			for session in selectedSessions:
				userObj.sessions.add(session)
				
			return redirect('profileApp:profile')
		
	def get(self, request):
		if not request.user.is_authenticated:
			return redirect(login_redirect_url)
		if not Setting.objects.first().canChangeSessions:
			return render(request, 'error.html', {})
		if not StudentInfo.objects.filter(user=request.user).exists():
			return render(request, 'error.html', {})

		u = request.user

		info = get_object_or_404(StudentInfo, user=u)
		if Department.objects.filter(prequel=info.group, year=info.year).exists():
			context = {
				'curr_group': info.group,
				'allowed_groups': Department.objects.get(prequel=info.group, year=info.year).sequels.all(),
			}
			return render(request, 'sessionManagerApp/manage.html', context )

		sessions = StudentInfo.objects.get(user=request.user).sessions.all()
		context = {
			'allSessions': [x for x in Session.objects.all() if not SessionOnGoing(x, u) and not SessionCompleted(x, u) and PrerequistiesDone(x, u) and SessionSameGroup(x, u)],
			'userSessions': sessions,
			'allCourses': Course.objects.all(),
			'userTotalHours': sum([x.course.duration.hour for x in sessions]),
			'minHoursWeek': Setting.objects.all()[0].minHoursWeek,
			'maxHoursWeek': Setting.objects.all()[0].maxHoursWeek,
		}
		
		return render(request, 'sessionManagerApp/manage.html', context )
		
class ViewSessionsView(View):
	def get(self, request, session_id):
		if not request.user.is_authenticated:
			return redirect(login_redirect_url)
			
		session = get_object_or_404(Session, id=session_id)
		
		if not Professor.objects.filter(user=request.user).exists():
			return render(request, 'error.html', {})

		if Professor.objects.get(user=request.user) != session.professor:
			return render(request, 'error.html', {})

		return render(request, 'sessionManagerApp/view.html', {'session': session } )

class DropSessionView(View):
	def get(self, request, session_id):
		if not request.user.is_authenticated:
			return redirect(login_redirect_url)

		session = get_object_or_404(Session, id=session_id)
		return render(request, 'sessionManagerApp/drop.html', {'session': session})

class DropSession(View):
	def get(self, request, session_id):
		if not request.user.is_authenticated:
			return redirect(login_redirect_url)

		session = get_object_or_404(Session, id=session_id)
		student = get_object_or_404(StudentInfo, user=request.user)

		if student.sessions.filter(id=session.id).exists():
			student.sessions.remove(session)

		return redirect('profileApp:sessions')

class ChatView(View):
	def get(self, request, session_id):
		if not request.user.is_authenticated:
			return redirect(login_redirect_url)

		prof = False
		session = get_object_or_404(Session, id=session_id)

		# Checks if the user is a professor.
		if Professor.objects.filter(user=request.user).exists():
			# Checks if the professor isn't the session owner.
			if not session.professor == Professor.objects.get(user=request.user):
				return render(request, 'error.html', {})
			prof = True

		# If it's professor connecting, make the chat available.
		if prof == True:
			session.chatActive = True
			session.save()
		else: #Else check if the chat is active or not.
			if session.chatActive == False:
				return render(request, 'error.html', {})

		context = {
			'prof': prof,
			'session': session,
		}
		return render(request, 'sessionManagerApp/chat.html', context)

class CloseChatView(View):
	def get(self, request, session_id):
		if not request.user.is_authenticated:
			return redirect(login_redirect_url)

		session = get_object_or_404(Session, id=session_id)
		if Professor.objects.filter(user=request.user).exists() and session.professor == Professor.objects.get(user=request.user):
			session.chatActive = False
			session.save()
			return redirect('quizesApp:view', session_id=session_id)

		return render(request, 'error.html', {})

sessionManagerApp/templates/sessionManagerApp/chat.html
{% extends "layout.html" %}
{% block title %} Quizes {% endblock %}
{% block content %}
<div class="chat">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2>
                    {{session.course.name}} - Chat Room
                    {% if prof %}
                        <button class="btn btn-danger pull-right" onclick="location.href='{% url 'sessionManagerApp:close_chat' session.id %}'">Close the chat room.</button>
                    {% endif %}
                </h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="chat-container-shadow">
                    <div class="messages-container">
                        <ul class="list-group list-unstyled list-messages" style="padding-top: 20px;">
                            
                        </ul>
                    </div>
                    <div class="input-container">
                        <div class="row">
                            <div class="col-md-11">
                                <div class="input-group">
                                    <div class="input-group-addon">Message</div>
                                    <input type="text" class="form-control" id='message' onkeydown="send_text_key(event);">
                                </div>  
                            </div>
                            <div class="col-md-1">
                                <button type="submit" class="btn btn-default btn-block" onclick="send_text();" style="margin-left: 0px;">Send</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-3" hidden>
                <div class="users-list-container">
                    <div class="test">
                        <h3>Users</h3>
                    </div>
                    <div class="list-group list-users" style="padding-top: 20px;">
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js_code %}
<script>
    let ws = '';

    function add_message_text(text){
        $('.list-messages').append(
            `<li class="list-group-item">${text}</li>`
        );
    }

    $(function(){
        add_message_text('Connecting to server...');
        let protocol = (location.protocol == 'https:')?'wss:':'ws:';
        
        ws = new WebSocket(`${protocol}//${location.host}/sessions/{{session.id}}`)

        ws.onopen = function(){
            add_message_text('Connected.');
        };
        ws.onmessage = function(e){
            // Parse the incoming JSON dictionary.
            message = JSON.parse(e.data);

            // Show the incoming message to the user.
            add_message_text(message.text);

            // On user connected, add them to the users list.
            for(var name of message.add_users){
                add_user(name['name']);
            }

            // Remove the user if disconnected.
            for(var name of message.remove_users){
                remove_user(name['name']);
            }
        }

        ws.onclose = function(e){
            add_message_text(`Disconnected. Erorr code: ${e.code}`);
        }

        ws.onerror = function(){
            add_message_text('Error occurred, disconnecting from chat.');
        }
    });

    // Sends specified text to the connected websocket.
    function send_manual_text(message){
        ws.send(message);
    }

    // Sends the chat input to the server websocket and clears the input.
    function send_text(){
        var message = $("#message").val();
        ws.send(message);
        $("#message").val("");
    }

    // On enter keydown in the input, send the text.
    function send_text_key(e){
        if(e.which == 13)
            send_text();
    }

    // Add specific user to the users list
    function add_user(username){
        $('.list-users').append(
            `<a class="list-group-item">${username}</a>`
        );
    }

    // Remove specific user from the users list
    function remove_user(username){
        var childList = $('.list-users').children();
        for(var x=0; x<childList.length; x++)
        {
            if(childList[x].innerText == username){
                childList[x].remove();
            }
        }
    }

    window.onbeforeunload = function(e){
        ws.close(0);
    }
</script>
{% endblock %}

sessionManagerApp/templates/sessionManagerApp/drop.html
{% extends "layout.html" %}
{% block title %} Are you sure? {% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="container">
        <h3>Are you sure you want to drop {{session.course.name}}? <br/> This is not reversable.</h3>
        <center>
            <button onclick="location.href='{% url 'sessionManagerApp:drop' session.id %}'" class="btn btn-success"><b>Yes</b></button>
            <button onclick="location.href='{% url 'quizesApp:view' session.id %}'" class="btn btn-warning"><b>No</b></button>
        </center>
    </div>
</div>
{% endblock %}

sessionManagerApp/templates/sessionManagerApp/error.html
{% extends "sessionManagerApp/header.html" %}
{% block title %} NO PERMISSIONS {% endblock %}
{% block manageActive %} active {% endblock %}
{% block bodyStyle %}
	background-color: #333;
	display: table;
	width: 100%;
	height: 100%; /* For at least Firefox */
	min-height: 100%;
	color: #fff;
	text-align: center;
{% endblock %}

{% block content %}
	<div class="site-wrapper">
		<div class="site-wrapper-inner">
			<div class="cover-container">
				<div class="inner cover">
					<h1 class="cover-heading">You don't have the permission!</h1>
					<p class="lead">
						Oops, you arrived here. It appears you don't have permissions to do so.
					</p>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

sessionManagerApp/templates/sessionManagerApp/header.html
{% load static %}

<!doctype html>
<html lang="en">
	<head>
		<title>{% block title %} {% endblock %} - Helwan University, Faculty of Science</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" type="text/css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> -->
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
		<link rel="stylesheet" href="{% static 'css/login.css' %}"/>
	</head>
	<body style="{%block bodyStyle%}{%endblock%}"> <!-- style="{%block bodysStyle%}{%endblock%} background-image: url('{% block bgImage %}{% endblock %}')" -->
		<nav class="navbar navbar-default">
			<div class="container-fluid">
			    <div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<span class="navbar-brand">HU Faculty of Science</span>
				</div>
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li class="{% block manageActive %} {% endblock %}"><a href="{% url 'sessionManagerApp:manage' %}">Manage semester courses<span class="sr-only">(current)</span></a></li>
						<li class="{% block coursesActive %} {% endblock %}"><a href="{% url 'coursesApp:courses' %}">Courses</a></li>
						<li class="{% block departmentsActive %} {% endblock %}"><a href="{% url 'departmentsApp:departments' %}">Departments</a></li>
					</ul>
					<ul class="nav navbar-nav navbar-right">
						{% comment "Dropdown Menu" %}
						<li class="dropdown">
							<a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
								Logged in as {{ user.first_name }} {{user.last_name}}<span class="caret"></span>
							</a>
							<ul class="dropdown-menu">
								<li><a href="{% url 'accountsApp:logout' %}">Logout</a></li>
								<!-- <li class="{% block notificationsActive %} {% endblock %}"><a href="#">Notifications</a></li> -->
								<li class="{% block profileActive %} {% endblock %}"><a href="{% url 'profileApp:profile' %}">Profile</a></li>
							</ul>
						</li>
						{% endcomment %}
						<li class="{% block profileActive %} {% endblock %}"><a href="{% url 'profileApp:profile' %}"><b>{{user}}</b> Profile</a></li>
						<li><a href="{% url 'accountsApp:logout' %}">Logout</a></li>
					</ul>
					
				</div>
			</div>
		</nav>

		{% block content %} {% endblock %}

		<footer class="footer">
			<font color="black">
				<center style="padding-top:20px;">2017 © Helwan University - Faculty of Science</center>
			</font>
		</footer>

		<!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" type="text/javascript" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" type="text/javascript" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" type="text/javascript" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script> -->
		<script src="{% static 'js/jquery.2.1.4.min.js' %}" type="text/javascript"></script>
		<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
		<script src="{% static 'js/date.js' %}" type="text/javascript"></script>

		{% block js_code %} {%endblock%}
	</body>
</html>

sessionManagerApp/templates/sessionManagerApp/view.html
{% extends "layout.html" %}
{% block title %} {{session.course.name}} Students {% endblock %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>{{session.course.name}} <div class="inline pull-right">{{session.startTime|time:"h:i A"}} - {{session.endTime|time:"h:i A"}}</div></h1>
            <h1>
                <small style="color:gray;">
                    Total Students: <span>{{session.studentinfo_set.count}}</span>
                </small>
            </h1>
            <hr/>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="list-group">
                {% for student in session.studentinfo_set.all %}
                    <a class="list-group-item"><b>{{student.full_name}}</b></a>
                {% empty %}
                    <a class="list-group-item">No one registered this course.</a>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}