husite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^news/', include('newsApp.urls')),
	url(r'^professors/', include('professorsApp.urls')),
	url(r'^events/', include('eventsApp.urls')),
	url(r'^', include('accountsApp.urls')),
	url(r'^sessions/', include('sessionManagerApp.urls')),
	url(r'^profile/', include('profileApp.urls')),
    url(r'^courses/', include('coursesApp.urls')),
    url(r'^departments/', include('departmentsApp.urls')),
    url(r'^assignments/', include('quizesApp.urls')),
    url(r'^lectures/', include('lecturesApp.urls')),
    url(r'exam/', include('onlineExamsApp.urls')),
    url(r'dashboard/', include('dashboard.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsApp/urls.py
from django.conf.urls import url
from .views import NewsHome, NewsArticleView, AddNewsView, EditNewsView, DeleteNewsView

app_name='newsApp'

urlpatterns = [
	url(r'^$', NewsHome.as_view(), name='NewsHomePage'),
    url(r'^(?P<page_num>[0-9]+)/$', NewsHome.as_view(), name='NewsPage'),
	url(r'^view/(?P<news_id>[0-9]+)/$', NewsArticleView.as_view(), name='newsArticle'),
	url(r'^delete/(?P<news_id>[0-9]+)/$', DeleteNewsView.as_view(), name='deleteNews'),
	url(r'^add/$', AddNewsView.as_view(), name='addNews'),
	url(r'^edit/(?P<news_id>[0-9]+)/$', EditNewsView.as_view(), name='editNews'),
]

newsApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class News(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	news_title = models.CharField(max_length=100)
	news_desc = models.CharField(max_length=5000)
	news_date = models.DateTimeField("Date published")
	
	def __str__(self):
		return self.news_title

newsApp/forms.py
from django.forms import ModelForm, Textarea
from .models import News
class AddNewsForm(ModelForm):
	# news_title = forms.CharField(label='Title', max_length=100)
	# news_desc = forms.CharField(label='Body', max_length=5000, widget=forms.Textarea)
	class Meta:
		model = News
		fields = ['news_title', 'news_desc']
		widgets = {
			'news_desc': Textarea()
		}

newsApp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404
from django.views import View
from django.utils import timezone
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login

from .models import News
from .forms import AddNewsForm


login_redirect_url = getattr(settings, 'LOGIN_URL', 'accountsApp:login')
news_shown_per_page = getattr(settings, 'NEWS_PER_PAGE', 5)

club_name = "NewspaperClub"
def HasPerm(user):
	return user.groups.filter(name=club_name).exists()

# Create your views here.

class NewsHome(View):
	def get(self, request, page_num='1'):
		startNews = ((int(page_num) - 1) * news_shown_per_page)
		next_page = ''
		prev_page = ''
		if News.objects.all().count() > (startNews + news_shown_per_page):
			next_page = int(page_num) + 1
		if int(page_num) > 1:
			prev_page = int(page_num) - 1
		context = {
			'latest_news': News.objects.order_by('-news_date')[startNews:(news_shown_per_page+startNews)],
			'next_page': next_page,
			'prev_page': prev_page,
			'has_perm': HasPerm(request.user),
		}
		return render(request, 'newsApp/index.html', context)
	
class DeleteNewsView(View):
	def get(self, request, news_id):
		if not HasPerm(request.user):
			return redirect(login_redirect_url)
		get_object_or_404(News, id=news_id).delete()
		return redirect('newsApp:NewsHomePage')
		
class NewsArticleView(View):
	def get(self, request, news_id):
		news = get_object_or_404(News, id=news_id)
		return render(request, 'newsApp/article.html', { 'news': news, 'has_perm': HasPerm(request.user) })
		

class AddNewsView(View):
	def post(self, request):
		if not HasPerm(request.user):
			return redirect(login_redirect_url)
		
		news = News(news_date=timezone.now(), user=request.user)
		form = AddNewsForm(request.POST, instance=news)
		if form.is_valid():
			form.save()
		else:
			return render(request, 'newsApp/addNews.html', { 'form': form })
		return redirect('newsApp:NewsHomePage')
	
	def get(self, request):
		if not HasPerm(request.user):
			return redirect(login_redirect_url)
			
		form = AddNewsForm()
		return render(request, 'newsApp/addNews.html', { 'form': form })
		
class EditNewsView(View):
	def post(self, request, news_id):
		if not HasPerm(request.user):
			return redirect(login_redirect_url)
			
		news = News(news_date=timezone.now(), user=request.user)
		form = AddNewsForm(request.POST, instance=get_object_or_404(News))
		if form.is_valid():
			form.save()
		else:
			return render(request, 'newsApp/editNews.html', { 'form': form})
		return redirect('newsApp:NewsHomePage')
	
	def get(self, request, news_id):
		if not HasPerm(request.user):
			return redirect(login_redirect_url)
			
		form = AddNewsForm(instance=get_object_or_404(News, id=news_id))
		return render(request, 'newsApp/editNews.html', { 'form': form})

newsApp/templates/newsApp/EditNews.html
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

newsApp/templates/newsApp/addNews.html
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

newsApp/templates/newsApp/article.html
<div style="margin:15px;">
{% if news %}
	<table>
		<td>
			<h1>
				{{news.news_title}}
			</h1>
		</td>
		<td>
			{% if has_perm %}
				<a href="{% url 'newsApp:editNews' news.id %}">Edit</a>
				<a href="{% url 'newsApp:deleteNews' news.id %}">Delete</a>
			{% endif %}
		</td>
	</table>
	<small style="color:gray;">Published by {{news.user.first_name}} {{news.user.last_name}} on {{news.news_date}}</small>
	<div style="margin:15px">
		{{news.news_desc}}
	</div>
{% else %}
	<p>There's no article with such ID</p>
{% endif %}
</div>

newsApp/templates/newsApp/index.html
<h1>News</h1>
{% if latest_news %}
	<ul>
		{% for news in latest_news %}
			<li>
				<a href="{% url 'newsApp:newsArticle' news.id %}">{{ news.news_title }}</a>
				<div style="margin:8px;">
					<script>
						document.write(("{{news.news_desc}}").substring(0, 100));
						{% if news.news_desc|length > 100 %}
							document.write("...");
						{% endif %}
					</script>
					{% if has_perm %}
						<a href="{% url 'newsApp:editNews' news.id %}">Edit</a>
						<a href="{% url 'newsApp:deleteNews' news.id %}">Delete</a>
					{% endif %}
				</div>
			</li>
		{% endfor %}
	</ul>
{% else %}
	<p>No news available</p>
{% endif %}

{% if prev_page %}
	<a href="{% url 'newsApp:NewsPage' prev_page %}">Previous</a>
{% endif %}

{% if next_page %}
	<a href="{% url 'newsApp:NewsPage' next_page %}">Next</a>
{% endif %}

{% if has_perm %}
	<a href="{% url 'newsApp:addNews' %}">Add news</a>
{% endif %}