husite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^news/', include('newsApp.urls')),
	url(r'^professors/', include('professorsApp.urls')),
	url(r'^events/', include('eventsApp.urls')),
	url(r'^', include('accountsApp.urls')),
	url(r'^sessions/', include('sessionManagerApp.urls')),
	url(r'^profile/', include('profileApp.urls')),
    url(r'^courses/', include('coursesApp.urls')),
    url(r'^departments/', include('departmentsApp.urls')),
    url(r'^assignments/', include('quizesApp.urls')),
    url(r'^lectures/', include('lecturesApp.urls')),
    url(r'exam/', include('onlineExamsApp.urls')),
    url(r'dashboard/', include('dashboard.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lecturesApp/urls.py
from django.conf.urls import url
from .views import LecturesView, DeleteLectureView

app_name = 'lecturesApp'

urlpatterns =[
    url(r'^(?P<session_id>[0-9]+)/$', LecturesView.as_view(), name='view'),
    url(r'^delete/(?P<lecture_id>[0-9]+)/$', DeleteLectureView.as_view(), name='delete'),
]

professorsApp/urls.py
# uncompyle6 version 2.13.2
# Python bytecode 3.5 (3350)
# Decompiled from: Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)]
# Embedded file name: D:\Programming\DjangoWebsite\HUWebsite\husite\professorsApp\urls.py
# Compiled at: 2017-10-30 06:07:23
# Size of source mod 2**32: 1166 bytes
from django.conf.urls import url
from .views import ProfessorListView, ProfessorView, CourseView, AddProfessorView, EditProfessorView, AddCourseView, EditCourseView, DeleteProfessorView, DeleteCourseView, CourseListView
app_name = 'professorsApp'
urlpatterns = [
	 url('^list/p/$', ProfessorListView.as_view(), name='home'),
	 url('^list/p/(?P<page_num>[0-9]+)/$', ProfessorListView.as_view(), name='homePage'),
	 url('^list/c/(?P<page_num>[0-9]+)/$', CourseListView.as_view(), name='coursePage'),
	 url('^view/p/(?P<prof_id>[0-9]+)/$', ProfessorView.as_view(), name='viewProf'),
	 url('^view/c/(?P<course_id>[0-9]+)/$', CourseView.as_view(), name='viewCourse'),
	 url('^add/p/$', AddProfessorView.as_view(), name='addProf'),
	 url('^add/c/$', AddCourseView.as_view(), name='addCourse'),
	 url('^edit/p/(?P<prof_id>[0-9]+)/$', EditProfessorView.as_view(), name='editProf'),
	 url('^edit/c/(?P<course_id>[0-9]+)/$', EditCourseView.as_view(), name='editCourse'),
	 url('^delete/p/(?P<prof_id>[0-9]+)/$', DeleteProfessorView.as_view(), name='deleteProf'),
	 url('^delete/c/(?P<course_id>[0-9]+)/$', DeleteCourseView.as_view(), name='deleteCourse')
 ]

quizesApp/urls.py
from django.conf.urls import url
from .views import QuizesView, DeleteQuizView, QuizResultsView


app_name='quizesApp'

urlpatterns = [
	url(r'^(?P<session_id>[0-9]+)/$', QuizesView.as_view(), name='view'),
	url(r'^delete/(?P<quiz_id>[0-9]+)/$', DeleteQuizView.as_view(), name='delete'),
	url(r'^view/(?P<quiz_id>[0-9]+)/$', QuizResultsView.as_view(), name='results'),
]

sessionManagerApp/urls.py
from django.conf.urls import url
from .views import ManageSessionsView, ViewSessionsView, DropSessionView, DropSession, ChatView, CloseChatView

app_name='sessionManagerApp'

urlpatterns = [
	url(r'^manage/$', ManageSessionsView.as_view(), name='manage'),
	url(r'^view/(?P<session_id>[0-9]+)/$', ViewSessionsView.as_view(), name='view'),
	url(r'^drop/view/(?P<session_id>[0-9]+)/$', DropSessionView.as_view(), name='drop_view'),
	url(r'^drop/(?P<session_id>[0-9]+)/$', DropSession.as_view(), name='drop'),
	url(r'^chat/(?P<session_id>[0-9]+?)/$', ChatView.as_view(), name='chat'),
	url(r'^chat/close/(?P<session_id>[0-9]+?)/$', CloseChatView.as_view(), name='close_chat')
]

quizesApp/models.py
from django.db import models
from studentsApp.models import StudentInfo
from sessionManagerApp.models import Session


class QuizComplete(models.Model):
    student = models.ForeignKey(StudentInfo, on_delete=models.CASCADE)
    answerFile = models.FileField(upload_to='answers/%Y/%m/%d/%H/%M/')
    grade = models.CharField(max_length=10, default="---")

    def __str__(self):
        return str(self.student.id) + " " + self.student.full_name

class Quiz(models.Model):
    session = models.ForeignKey(Session, on_delete=models.CASCADE)
    quizFile = models.FileField(upload_to='quizes/%Y/%m/%d/%H/%M/')
    studentsCompleted = models.ManyToManyField(QuizComplete, blank=True)
    deadline = models.DateTimeField()
    max_grade = models.IntegerField(default=10)

    def __str__(self):
        return str(self.id) + " - " + str(self.session)

quizesApp/views.py
import datetime

from django.conf import settings
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone
from django.views import View

from professorsApp.models import Professor
from sessionManagerApp.models import Session
from studentsApp.models import StudentInfo

from .models import Quiz, QuizComplete

login_redirect_url = getattr(settings, 'LOGIN_URL', 'accountsApp:login')
quizes_shown_per_page = getattr(settings, 'NEWS_PER_PAGE', 5)

#TODO Actually use this.
class _quiz: #Should I use this instead of the rubbish down there? xD
    def __init__(student, quiz):
        self.session = quiz.session
        self.quizFile = quiz.quizFile
        self.studentsCompleted = quiz.studentsCompleted
        self.deadline = quiz.deadline
        self.max_grade = quiz.max_grade
        
        if quiz.studentsCompleted.filter(student=student).exists():
            if quiz.studentsCompleted.filter(student=student).first().grade == '---':
                self.status = 'Reviewing Answer'
            else:
                self.status = 'Marked'
        else:
            if quiz.deadline <= timezone.now():
                self.status = 'Ended'
            self.status = 'Not uploaded.'

#TODO Actually implement this.
def HasPerm(user, session):
    # Has permission to delete quizes, view quizes results & change them.
	return True

class QuizesView(View):
    def get(self, request, session_id):
        if not request.user.is_authenticated:
            return redirect(login_redirect_url)

        session = get_object_or_404(Session, id=session_id)

        if session.professor is None:
            return render(request, 'error.html', {})

        prof = None
        if Professor.objects.filter(user=request.user).exists():
            prof = Professor.objects.get(user=request.user)

        if prof is None:
            student = get_object_or_404(StudentInfo, user=request.user)

            if not session in student.sessions.all():
                return render(request, 'error.html', {})
            
            
            quizes_grades = []

            for quiz in session.quiz_set.order_by('-id'):
                if quiz.studentsCompleted.filter(student=student).exists():
                    quizes_grades.append(quiz.studentsCompleted.get(student=student).grade)
                else:
                    if quiz.deadline <= timezone.now():
                        quizes_grades.append('Ended')
                    else:
                        quizes_grades.append('???')

            context = {
                'quizes': session.quiz_set.order_by('-id'),
                'quizes_grades': quizes_grades,
                'session': session,
                'has_perm': HasPerm(request.user, session)
            }
            
            return render(request, 'quizesApp/index.v2.html', context)
        else:
            if session.professor != prof:
                return render(request, 'error.html', {})

            context = {
                'quizes': session.quiz_set.order_by('-id'),
                'session': session,
                'prof': True,
                'has_perm': True,
            }

            context['colors'] = [y <= timezone.now() for y in [x.deadline for x in context['quizes']]]
            return render(request, 'quizesApp/index.v2.html', context)

    #TODO: We need to check 1 file sizes, file extensions.
    def post(self, request, session_id):
        if not request.user.is_authenticated:
            return redirect(login_redirect_url)
        
        session = get_object_or_404(Session, id=session_id)

        #If it's professor posting, it would be a quiz.
        if Professor.objects.filter(user=request.user).exists():
            if session.professor == None:
                return render(request, 'error.html', {})
            if session.professor != Professor.objects.get(user=request.user):
                return render(request, 'error.html', {})
            #TODO Check deadline, Check max_grade
            post_deadline = datetime.datetime.strptime(request.POST.get('date') + " " + request.POST.get('time'), '%Y-%m-%d %H:%M')
            quiz = Quiz(max_grade=request.POST.get('max_grade'), session=session, quizFile=request.FILES['quiz_file'], deadline=post_deadline)
            quiz.save()
            return redirect('quizesApp:view', session_id=session.id)


        student = get_object_or_404(StudentInfo, user=request.user)
        quiz = get_object_or_404(Quiz, id=request.POST.get('quiz_id'))

        # If the student doesn't take this session.
        if not session in student.sessions.all():
            return render(request, 'error.html', {})

        # If the quiz is not in a session the student takes.
        if not quiz in session.quiz_set.all():
            return render(request, 'error.html', {})
        
        # If the student already uploaded an answer.
        if quiz.studentsCompleted.filter(student=student).exists():
            return render(request, 'error.html', {})

        # If quiz already ended.
        if quiz.deadline <= timezone.now():
            return render(request, 'error.html', {})

        answer = QuizComplete(grade="---", answerFile=request.FILES['file'], student=student)
        answer.save()

        quiz.studentsCompleted.add(answer)

        return redirect('quizesApp:view', session_id=session.id)

class DeleteQuizView(View):
    def get(self, request, quiz_id):
        if not request.user.is_authenticated:
            return redirect(login_redirect_url)

        quiz = get_object_or_404(Quiz, id=quiz_id)
        
        if not HasPerm(request.user, quiz.session):
            return render(request, 'error.html', {})

        quiz.delete()

        return redirect('quizesApp:list', kwargs={'session_id': quiz.session.id})

class QuizResultsView(View):
    def get(self, request, quiz_id):
        if not request.user.is_authenticated:
            return redirect(login_redirect_url)

        quiz = get_object_or_404(Quiz, id=quiz_id)

        if not HasPerm(request.user, quiz.session):
            return render(request, 'error.html', {})

        context = {
            'quiz': quiz,
            'answers': quiz.studentsCompleted.all(),
            'grades': range(0, quiz.max_grade+1),
        }

        return render(request, 'quizesApp/quizResults.html', context)

    def post(self, request, quiz_id):
        if not request.user.is_authenticated:
            return redirect(login_redirect_url)

        quiz = get_object_or_404(Quiz, id=quiz_id)

        if not HasPerm(request.user, quiz.session):
            return render(request, 'error.html', {})

        grades = request.POST.getlist('grade')
        i = 0
        for answer in quiz.studentsCompleted.all():
            answer.grade = grades[i]
            i = i + 1
            answer.save()
        
        return redirect('quizesApp:view', session_id=quiz.session.id)

quizesApp/templates/quizesApp/index.html
{% extends "layout.html" %}
{% block title %} Assignments {% endblock %}
{% block content %}

{% load index %}

<div class="alert alert-danger hidden">
    <strong>Error!</strong> 
    <div class="errors inline">

    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>{{session.course.name}} <div class="inline pull-right">{{session.startTime|time:"h:i A"}} - {{session.endTime|time:"h:i A"}}</div></h1>
            <h1>
                <small style="color:gray;">
                    {% if not prof %}
                        <div class="row">
                            <div class="col-md-8">
                                Professor: <a href="{% url 'professorsApp:viewProf' session.professor.id %}">{{session.professor}}</a>
                            </div>
                            <div class="col-md-4">
                                <button onclick="location.href='{% url 'sessionManagerApp:drop_view' session.id %}'" class="pull-right btn btn-danger"><b>Drop Course</b></button>
                            </div>
                        </div>
                    {% else %}
                        Total Students: <span>{{session.studentinfo_set.count}}</span>
                    {% endif %}
                </small>
            </h1>
            <hr/>
        </div>
    </div>

    <ul class="nav nav-tabs" id="myTabs">
        <li class="active"><a href="{% url 'quizesApp:view' session.id %}">Assignments</a></li>
        <li><a href="{% url 'lecturesApp:view' session.id %}">Lecture Files</a></li>
    </ul>

    <div class="row">
        <div class="col-md-12">
            <div class="list-group">
                {% for quiz in quizes %}
                    {% if not prof %}
                        <a class="list-group-item 
                            {% if quizes_grades|index:forloop.counter0 != '???' %}
                                list-group-item-success
                            {%endif%}
                            {% if quizes_grades|index:forloop.counter0 == '---' %}
                                list-group-item-warning
                            {% endif %}
                            {% if quizes_grades|index:forloop.counter0 == 'Ended' %}
                                list-group-item-danger
                            {% endif %}
                            ">
                            <div class="row pgRow">
                                <div class="col-md-3">
                                    <b>Deadline</b> <span class="date">{{quiz.deadline|date:"M. d, Y, "}}</span> <span class="time">{{quiz.deadline|time:"h:i A"}}</span>
                                </div>
                                <div class="col-md-2">
                                    <b>Grade</b> <span class="grade"> {{quizes_grades|index:forloop.counter0}} / {{quiz.max_grade}}</span>
                                </div>
                                <div class="col-md-2">
                                    <span class="status">
                                        {% if quizes_grades|index:forloop.counter0 == '???' %}
                                            <b>Not answered.</b>
                                        {% elif quizes_grades|index:forloop.counter0 == '---' %}
                                            <b>Reviewing answer.</b>
                                        {% elif quizes_grades|index:forloop.counter0 == 'Ended' %}
                                            <b>Deadline ended.</b>
                                        {% else %}
                                            <b>Answer Marked.</b>
                                        {%endif%}
                                    </span>
                                </div>
                                <div class="col-md-5">
                                    <div class="pull-right">
                                        <button onclick="location.href='{{quiz.quizFile.url}}'" class="btn btn-default"><b>Download Quiz</b> <span class="glyphicon glyphicon-download-alt"/></button>
                                        {% if quizes_grades|index:forloop.counter0 == '???' %}
                                            <form id="form" method="POST" action="" class="inline" enctype="multipart/form-data">
                                                {% csrf_token %}
                                                <label class="btn btn-default"><b>Upload Answer</b> <span class="glyphicon glyphicon-upload"/><input accept=".jpg, .jpeg, .png, .doc, .docx, .pdf" id="file" name='file' type="file" style="display:none;"></label>
                                                <input type=hidden name='quiz_id' value="{{quiz.id}}">
                                            </form>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </a>
                    {% else %}
                        <a class='list-group-item {% if colors|index:forloop.counter0 %}list-group-item-danger{%endif%}'>
                            <div class="row pgRow">
                                <div class="col-md-3">
                                    <b>Deadline</b> <span class="date">{{quiz.deadline|date:"M. d, Y, "}}</span> <span class="time">{{quiz.deadline|time:"h:i A"}}</span>
                                </div>
                                <div class="col-md-2">
                                    <b>Max Grade</b> <span class="grade"> {{quiz.max_grade}}</span>
                                </div>
                                <div class="col-md-3">
                                    <b>Status</b> 
                                    <span class="grade">
                                        {% if colors|index:forloop.counter0 %}
                                            Ended
                                        {% else %}
                                            Running
                                        {% endif %}
                                    </span>
                                </div>
                                <div class="col-md-4">
                                    <div class="pull-right">
                                        <button onclick="location.href='{{quiz.quizFile.url}}'" class="btn btn-default"><b>Download Assignmment</b> <span class="glyphicon glyphicon-download-alt"/></button>
                                        <button class="btn btn-default" onclick="location.href='{% url 'quizesApp:delete' quiz.id %}'"><b>Delete</b> <span class="glyphicon glyphicon-trash"/></button>
                                        <button class="btn btn-default" onclick="location.href='{% url 'quizesApp:results' quiz.id %}'"><b>Results</b> <span class="glyphicon glyphicon-signal"/></button>
                                    </div>
                                </div>
                            </div>
                        </a>
                    {% endif %}
                {% empty %}
                    <a class="list-group-item">There's no assignments right now.</a>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="pull-right">
                {% if prof %}
                    <button onclick="location.href='{% url 'sessionManagerApp:view' session.id %}'" class="btn btn-default"><b>View Session Students</b> <span class="glyphicon glyphicon-th-list"/></button>
                    <button class="btn btn-default" data-toggle="modal" data-target="#myModal"><b>Add new assignment</b> <span class="glyphicon glyphicon-edit"/></button>
                {% endif %}
            </div>
        </div>
    </div>
    
    <div class="modal" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel">Add new assignment to {{session.course.name}}</h4>
            </div>
            <div class="modal-body">
            <form id="add_quiz_form" method="POST" action="" enctype="multipart/form-data" class="form-horizontal">
                {% csrf_token %}
                <div class="form-group">
                    <label class="col-md-3 control-label">Deadline date: </label>
                    <div class="col-md-8">
                        <input type="date" class="form-control" name="date"/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">Deadline time: </label>
                    <div class="col-md-8">
                        <input type="time" class="form-control" name="time" value="13:00"/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">Grade: </label>
                    <div class="col-md-8">
                        <input type="number" min="1" max="100" class="form-control" name="max_grade"/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">Quiz file: </label>
                    <div class="col-md-8">
                        <label class="btn btn-default">
                            Upload file <span class="glyphicon glyphicon-upload"></span>
                            <input id="file-selector" name="quiz_file" type="file" class="form-control" accept=".jpg, .jpeg, .png, .doc, .docx, .pdf" style="display:none;" onchange="$('#upload-file-info').html(this.files[0].name)"/>
                        </label>
                        <span class='label label-success' id="upload-file-info"></span><br/>
                        <span class='label label-danger' id="upload-file-error"></span>
                        <p class="help-block">
                            Allowed extensions: doc, docx, jpg, jpeg, png and pdf. <br> Max file size: 8 MB.
                        </p>
                    </div>
                </div>
            </form>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary" id="submit_btn" onclick="$('#add_quiz_form').submit()">Add Assignment</button>
            </div>
          </div>
        </div>
      </div>
</div>
{% endblock %}


{% block js_code %}
<script>

var allowed_extensions = ["doc", "docx", "jpg", "jpeg", "png", "pdf"];
var user_max_quiz_filesize = 8;
var prof_max_quiz_filesize = 8;

if(document.getElementById('file')){
    document.getElementById("file").onchange = function() {
        var fileSize = this.files[0].size/1024/1024;
        var fileExtension = this.files[0].name.split('.').pop();
        if(fileSize <= user_max_quiz_filesize && allowed_extensions.indexOf(fileExtension) != -1) //Max file size HERE. TODO make it a value in settings.
        {
            document.getElementById("form").submit();
        } else {
            document.getElementsByClassName("alert")[0].setAttribute("class", "alert alert-danger")
            document.getElementsByClassName("errors")[0].innerHTML = "File exceeded the maximum size " + user_max_quiz_filesize + "MB. Or it's not allowed.";
        }
        
    };
}

// Professor upload.
if(document.getElementById('file-selector')){
    document.getElementById("file-selector").onchange = function() {
        var fileSize = this.files[0].size/1024/1024;
        var fileExtension = this.files[0].name.split('.').pop();
        if(fileSize <= prof_max_quiz_filesize && allowed_extensions.indexOf(fileExtension) != -1) //Max file size HERE. TODO make it a value in settings.
        {
            $("#upload-file-error").text("");
            document.getElementById("submit_btn").setAttribute("onclick", "$('#add_quiz_form').submit()")
            document.getElementById("submit_btn").classList.remove("disabled");
        } else {
            $("#upload-file-error").text("File exceeded the maximum size. Or it's not allowed.");
            document.getElementById("submit_btn").setAttribute("onclick", "")
            document.getElementById("submit_btn").classList.add("disabled");
        }
    };
}
$('#file-selector').change(function(){

});
</script>
{%  endblock %}

quizesApp/templates/quizesApp/quizResults.html
{% extends "layout.html" %}
{% block title %} Quiz results {% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>{{quiz.session.course.name}} - Quiz results</h1>
            <h1>
                <small style="color:gray;">
                    <div class="inline pull-right"><b>Deadline</b> {{quiz.deadline}} </div>
                    <b>Students answered</b> <span> {{answers.count}} / {{quiz.session.studentinfo_set.count}} </span>
                </small>
            </h1>
            <hr/>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <form action="" method="POST">
                {% csrf_token %}
                <div class="list-group">
                    {% for student_answer in answers %}
                        <a class="list-group-item
                            {% if student_answer.grade != '---' %}
                                list-group-item-success
                            {% endif %}">
                            <div class="row pgRow">
                                <div class="col-md-4">
                                    <b>{{student_answer.student.full_name}}</b>
                                </div>
                                <div class="col-md-1">
                                    <b>Grade</b> <!-- <input class="form-control" type="text" value="{{student_answer.grade}}"/> -->
                                </div>
                                <div class="col-md-3">
                                    <select class="form-control" name="grade">
                                        <option value='---'>---</option>
                                        {% for grade in grades %}
                                            <option value='{{grade}}' {% if student_answer.grade == grade|stringformat:"i" %} selected="selected" {%endif%}>{{grade}}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="col-md-4">
                                    <div class="pull-right">
                                        <button onclick="location.href='{{student_answer.answerFile.url}}'" type="button" class="btn btn-default"><b>View answer</b></button>
                                    </div>
                                </div>
                            </div>
                        </a>
                    {% empty %}
                        <a class="list-group-item">There's no answers yet!</a>
                    {% endfor %}
                </div>
                <button class="btn btn-default pull-right"><b>Save changes</b></button>
            </form>
        </div>
    </div>
</div>
{% endblock %}