coursesApp/urls.py
from django.conf.urls import url
from .views import CoursesViewVersion2, CourseView

app_name='coursesApp'

urlpatterns = [
	url(r'^$', CoursesViewVersion2.as_view(), name='courses'),
	url(r'^(?P<course_id>[0-9]+)/$', CourseView.as_view(), name='view_course'),
]

husite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^news/', include('newsApp.urls')),
	url(r'^professors/', include('professorsApp.urls')),
	url(r'^events/', include('eventsApp.urls')),
	url(r'^', include('accountsApp.urls')),
	url(r'^sessions/', include('sessionManagerApp.urls')),
	url(r'^profile/', include('profileApp.urls')),
    url(r'^courses/', include('coursesApp.urls')),
    url(r'^departments/', include('departmentsApp.urls')),
    url(r'^assignments/', include('quizesApp.urls')),
    url(r'^lectures/', include('lecturesApp.urls')),
    url(r'exam/', include('onlineExamsApp.urls')),
    url(r'dashboard/', include('dashboard.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

professorsApp/urls.py
# uncompyle6 version 2.13.2
# Python bytecode 3.5 (3350)
# Decompiled from: Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)]
# Embedded file name: D:\Programming\DjangoWebsite\HUWebsite\husite\professorsApp\urls.py
# Compiled at: 2017-10-30 06:07:23
# Size of source mod 2**32: 1166 bytes
from django.conf.urls import url
from .views import ProfessorListView, ProfessorView, CourseView, AddProfessorView, EditProfessorView, AddCourseView, EditCourseView, DeleteProfessorView, DeleteCourseView, CourseListView
app_name = 'professorsApp'
urlpatterns = [
	 url('^list/p/$', ProfessorListView.as_view(), name='home'),
	 url('^list/p/(?P<page_num>[0-9]+)/$', ProfessorListView.as_view(), name='homePage'),
	 url('^list/c/(?P<page_num>[0-9]+)/$', CourseListView.as_view(), name='coursePage'),
	 url('^view/p/(?P<prof_id>[0-9]+)/$', ProfessorView.as_view(), name='viewProf'),
	 url('^view/c/(?P<course_id>[0-9]+)/$', CourseView.as_view(), name='viewCourse'),
	 url('^add/p/$', AddProfessorView.as_view(), name='addProf'),
	 url('^add/c/$', AddCourseView.as_view(), name='addCourse'),
	 url('^edit/p/(?P<prof_id>[0-9]+)/$', EditProfessorView.as_view(), name='editProf'),
	 url('^edit/c/(?P<course_id>[0-9]+)/$', EditCourseView.as_view(), name='editCourse'),
	 url('^delete/p/(?P<prof_id>[0-9]+)/$', DeleteProfessorView.as_view(), name='deleteProf'),
	 url('^delete/c/(?P<course_id>[0-9]+)/$', DeleteCourseView.as_view(), name='deleteCourse')
 ]

profileApp/urls.py
from django.conf.urls import url

from .views import ProfileHomeView, ScheduleView, OldSemestersView, SessionsView

app_name = 'profileApp'

urlpatterns = [
	url(r'^$', ProfileHomeView.as_view(), name='profile'),
	url(r'^schedule/$', ScheduleView.as_view(), name='schedule'),
	url(r'^semesters/$', OldSemestersView.as_view(), name='semesters'),
	url(r'^sessions/$', SessionsView.as_view(), name='sessions'),
]

quizesApp/urls.py
from django.conf.urls import url
from .views import QuizesView, DeleteQuizView, QuizResultsView


app_name='quizesApp'

urlpatterns = [
	url(r'^(?P<session_id>[0-9]+)/$', QuizesView.as_view(), name='view'),
	url(r'^delete/(?P<quiz_id>[0-9]+)/$', DeleteQuizView.as_view(), name='delete'),
	url(r'^view/(?P<quiz_id>[0-9]+)/$', QuizResultsView.as_view(), name='results'),
]

profileApp/models.py
from django.db import models
from studentsApp.models import StudentInfo
from coursesApp.models import Course
# Create your models here.

class PublicNotification(models.Model):
	showToStudents = models.BooleanField(default=True)
	showToProfessors = models.BooleanField(default=False)
	notification = models.CharField(max_length=100)

	def __str__(self):
		return self.notification[:100]

class UserSemester(models.Model):
	info = models.ForeignKey(StudentInfo, on_delete=models.CASCADE)
	GPA = models.FloatField(default=0.0)

	def updateGPA(self): # TODO: Fix this, this is temporary.
		gpa = 0.0
		for c_c in self.completedcourse_set.all():
			gpa += ((c_c.written_result + c_c.oral_result + c_c.app_result) / 
				(c_c.course.max_written_result + c_c.course.max_oral_result + c_c.course.max_app_result) / 2)
		self.GPA = gpa
		self.save()

	def __str__(self):
		return str(self.id) + "# " + self.info.user.first_name + " " + self.info.user.last_name

class CompletedCourse(models.Model):
	semester = models.ForeignKey(UserSemester, on_delete=models.CASCADE)
	course = models.ForeignKey(Course, on_delete=models.CASCADE)
	written_result = models.IntegerField()
	oral_result = models.IntegerField()
	app_result = models.IntegerField()
	
	def save(self, *args, **kwargs):
		self.semester.updateGPA()
		super(CompletedCourse, self).save(*args, **kwargs)

	def __str__(self):
		return str(self.course)

profileApp/views.py
from django.conf import settings
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.views import View

from professorsApp.models import Professor
from sessionManagerApp.models import Session
from studentsApp.models import StudentInfo

from .models import PublicNotification

login_redirect_url = getattr(settings, 'LOGIN_URL', 'accountsApp:login')


class daySessions:
    def __init__(self, sessions, day):
        self.sessions = sessions
        self.day = day
    sessions = None
    day = None


class ProfileHomeView(View):
    def get(self, request):
        if not request.user.is_authenticated:
            return redirect(login_redirect_url)

        prof = None
        student = None

		# Could also use StudentInfo to check.
        if Professor.objects.filter(user=request.user).exists():
            prof = Professor.objects.get(user=request.user)
            notifications = PublicNotification.objects.filter(showToProfessors=True)
        else:
            student = StudentInfo.objects.get(user=request.user)
            notifications = PublicNotification.objects.filter(showToStudents=True)

        context = {
            'notifications': notifications,
            'professor': prof,
            'student': student,
        }
        return render(request, 'profileApp/home.html', context)


class ScheduleView(View):
    def get(self, request):
        if not request.user.is_authenticated:
            return redirect(login_redirect_url)

        prof = None
        student = None

		# Could also use StudentInfo to check.
        if Professor.objects.filter(user=request.user).exists():
            prof = Professor.objects.get(user=request.user)
            notifications = PublicNotification.objects.filter(showToProfessors=True)
        else:
            student = StudentInfo.objects.get(user=request.user)
            notifications = PublicNotification.objects.filter(showToStudents=True)

        context = {
			'professor': prof,
			'sessions': [],
			'notifications': notifications,
		}
        
        if prof:
            for day in Session.DAYS_OF_WEEK_CHOICES:
                context['sessions'].append(daySessions(prof.session_set.filter(dayOfWeek=day[0]).order_by('startTime'), day[1]))
        else:
            for day in Session.DAYS_OF_WEEK_CHOICES:
                context['sessions'].append(daySessions(student.sessions.filter(dayOfWeek=day[0]).order_by('startTime'), day[1]))

        context['maxLectures'] = range(
            max([len(x.sessions) for x in context['sessions']]))

        return render(request, 'profileApp/schedule.html', context)


class OldSemestersView(View):
    def get(self, request):
        if not request.user.is_authenticated:
            return redirect(login_redirect_url)

        student = get_object_or_404(StudentInfo, user=request.user)

        context = {
            'notifications': PublicNotification.objects.filter(showToStudents=True),
            'semesters': student.usersemester_set.all(),
        }
        return render(request, 'profileApp/semesters.html', context)

class SessionsView(View):
    def get(self, request):
        if not request.user.is_authenticated:
            return redirect(login_redirect_url)

        prof = None
        student = None

		# Could also use StudentInfo to check.
        if Professor.objects.filter(user=request.user).exists():
            prof = Professor.objects.get(user=request.user)
            notifications = PublicNotification.objects.filter(showToProfessors=True)
        else:
            student = StudentInfo.objects.get(user=request.user)
            notifications = PublicNotification.objects.filter(showToStudents=True)

        context = {
            'notifications': notifications,
            'professor': prof,
            'student': student,
        }
        return render(request, 'profileApp/current_sessions.html', context)

profileApp/templates/profileApp/current_sessions.html
{% extends "layout.html" %}
{% block title %} {{user.first_name}} {{user.last_name}} Sessions {% endblock %}
{% block profileActive %} active {% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="alert alert-warning" role="alert" style="margin:10px;{% if not notifications %} display:none; {% endif %}">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <div class="errors" style="display:inline;">
                {% for notify in notifications %}
                    {{notify}} <br>
                {% endfor %}
            </div>
        </div>
    </div>
</div>


{% if professor %}
<div class="container">
    <ul class="nav nav-tabs" id="myTabs">
        <li><a href="{% url 'profileApp:profile' %}">Profile</a></li>
        <li><a href="{% url 'profileApp:schedule' %}">Schedule</a></li>
        <li class="active"><a href="{% url 'profileApp:sessions' %}">Sessions</a></li>
    </ul>
    <div class="list-group">
        {% for session in professor.session_set.all %}
            <a href="{% url 'quizesApp:view' session.id%}" class="list-group-item">{{session.course.name}}</a>
        {% endfor %}
    </div>
</div>
{% else %}
<div class="container">
    <ul class="nav nav-tabs" id="myTabs">
        <li><a href="{% url 'profileApp:profile' %}">Profile</a></li>
        <li><a href="{% url 'profileApp:schedule' %}">Schedule</a></li>
        <li><a href="{% url 'profileApp:semesters' %}">Old Semesters</a></li>
        <li class="active"><a href="{% url 'profileApp:sessions' %}">Sessions</a></li>
        <li><a href="#">Messages</a></li>
    </ul>
    <div class="list-group">
        {% for session in student.sessions.all %}
            {% if session.professor %}
                <a href="{% url 'quizesApp:view' session.id %}" class="list-group-item">
                    {{session.course.name}} - {{session.get_dayOfWeek_display}} - <b>{{session.professor}}</b>
                </a>
            {% else %}
                <a href="#" class="list-group-item disabled">
                    {{session.course.name}} - {{session.get_dayOfWeek_display}} - <b>Not available.</b>
                </a>
            {% endif %}
        {% empty %}
            <a class="list-group-item">You don't have any sessions.</a>
        {% endfor %}
    </div>
</div>

{%endif%}
{% endblock %}

profileApp/templates/profileApp/home.html
{% extends "layout.html" %}
{% block title %} {{user.first_name}} {{user.last_name}} Profile {% endblock %}
{% block profileActive %} active {% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="alert alert-warning" role="alert" style="margin:10px;{% if not notifications %} display:none; {% endif %}">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <div class="errors" style="display:inline;">
                {% for notify in notifications %}
                    {{notify}} <br>
                {% endfor %}
            </div>
        </div>
    </div>
</div>


{% if professor %}
<div class="container">
    <ul class="nav nav-tabs" id="myTabs">
        <li class="active"><a href="{% url 'profileApp:profile' %}">Profile</a></li>
        <li><a href="{% url 'profileApp:schedule' %}">Schedule</a></li>
        <li><a href="{% url 'profileApp:sessions' %}">Sessions</a></li>
    </ul>
    <div class="row">
        <div class="col-md-12">
            <h1><b>{{professor.name}}</b></h1>
            <h1>
                <small style="color:gray;">
                    <!-- Quick info here.. -->
                </small>
            </h1>
            <hr/>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h3>{{professor.info|linebreaks}}</h3>
        </div>
    </div>
</div>
{% else %}

<div class="container">
    <ul class="nav nav-tabs" id="myTabs">
        <ul class="nav nav-tabs" id="myTabs">
            <li class="active"><a href="{% url 'profileApp:profile' %}">Profile</a></li>
            <li><a href="{% url 'profileApp:schedule' %}">Schedule</a></li>
            <li><a href="{% url 'profileApp:semesters' %}">Old Semesters</a></li>
            <li><a href="{% url 'profileApp:sessions' %}">Sessions</a></li>
            <li><a href="#">Messages</a></li>
        </ul>
    </ul>
    <div class="row">
        <div class="col-md-12">
            <div class="tab-content">
                <div class="tab-pane fade in active" id="profile">
                    <table class="table table-condensed">
                        <tr>
                            <td width=150>ID</td><td>{{student.college_id}}</td>
                        </tr>
                        <tr>
                            <td>Name</td><td>{{student.full_name}}</td>
                        </tr>
                        <tr>
                            <td>Year</td><td>{{student.year}}</td>
                        </tr>
                        <tr>
                            <td>Departments</td><td>{{student.group}}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
<!--     <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Communication courses available # TODO
                </div>
                <div class="list-group">
                    {% for session in student.sessions.all %}
                        {% if session.professor %}
                            <a href="{% url 'quizesApp:view' session.id %}" class="list-group-item">
                                <b>{{session.course}} - {{session.get_dayOfWeek_display}} by {{session.professor}}</b>
                            </a>
                        {% else %}
                            <a href="#" class="list-group-item disabled">
                                {{session.course}} - {{session.get_dayOfWeek_display}}. <b>Not available.</b>
                            </a>
                        {% endif %}
                    {% empty %}
                        <a class="list-group-item">You don't have any sessions.</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div> -->
</div>

{%endif%}
{% endblock %}

profileApp/templates/profileApp/schedule.html
{% extends "layout.html" %}
{% block title %} {{user.first_name}} {{user.last_name}} Schedule {% endblock %}
{% block profileActive %} active {% endblock %}
{% block content %}
<div class="row">
        <div class="col-md-12">
            <div class="alert alert-warning" role="alert" style="margin:10px;{% if not notifications %} display:none; {% endif %}">
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                <div class="errors" style="display:inline;">
                    {% for notify in notifications %}
                        {{notify}} <br>
                    {% endfor %}
                </div>
            </div>
        </div>
</div>

<div class="container">
    {% if professor %}
        <ul class="nav nav-tabs" id="myTabs">
            <li><a href="{% url 'profileApp:profile' %}">Profile</a></li>
            <li class="active"><a href="{% url 'profileApp:schedule' %}">Schedule</a></li>
            <li><a href="{% url 'profileApp:sessions' %}">Sessions</a></li>
        </ul>
    {% else %}
        <ul class="nav nav-tabs" id="myTabs">
            <li><a href="{% url 'profileApp:profile' %}">Profile</a></li>
            <li class="active"><a href="{% url 'profileApp:schedule' %}">Schedule</a></li>
            <li><a href="{% url 'profileApp:semesters' %}">Old Semesters</a></li>
            <li><a href="{% url 'profileApp:sessions' %}">Sessions</a></li>
            <li><a href="#">Messages</a></li>
        </ul>
    {% endif %}
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-condensed">
                    <tr>
                        <td></td>
                        {% for lec in maxLectures %}
                            <td class="text-center">{{forloop.counter}}</td>
                        {% endfor %}
                    </tr>
                        {% for day_session in sessions %}
                            {% if day_session.sessions %}
                                <tr>
                                    <td width=100>{{day_session.day}}</td>
                                    {% for session in day_session.sessions %}
                                        <td class="fixWidth text-center">
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <a href="{% url 'coursesApp:view_course' session.course.id %}" class="sessionCourse">{{session.course.code}}</a>
                                                    <span class="inline">{{session.startTime|time:"h:i"}} - {{session.endTime|time:"h:i"}}</span><br>
                                                    <small style="color:gray">By 
                                                        {% if session.professor %}
                                                            <a href="{% url 'professorsApp:viewProf' session.professor.id %}" target="_blank">{{session.professor}}</a> 
                                                        {% else %}
                                                            undefined
                                                        {% endif %} 
                                                        / {{session.location}}
                                                    </small>
                                                </div>
                                                <div class="col-md-6 text-center">
                                                    <div class="row">
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                    {% endfor %}
                                </tr>
                            {%endif%}
                        {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

profileApp/templates/profileApp/semesters.html
{% extends "layout.html" %}
{% block title %} {{user.first_name}} {{user.last_name}} Semesters {% endblock %}
{% block profileActive %} active {% endblock %}
{% block content %}
<div class="row">
        <div class="col-md-12">
            <div class="alert alert-warning" role="alert" style="margin:10px;{% if not notifications %} display:none; {% endif %}">
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                <div class="errors" style="display:inline;">
                    {% for notify in notifications %}
                        {{notify}} <br>
                    {% endfor %}
                </div>
            </div>
        </div>
</div>

<div class="container">
    <ul class="nav nav-tabs" id="myTabs">
        <li><a href="{% url 'profileApp:profile' %}">Profile</a></li>
        <li><a href="{% url 'profileApp:schedule' %}">Schedule</a></li>
        <li class="active"><a href="{% url 'profileApp:semesters' %}">Old Semesters</a></li>
        <li><a href="{% url 'profileApp:sessions' %}">Sessions</a></li>
        <li><a href="#">Messages</a></li>
    </ul>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-md-6">
                            Previous Semesters
                        </div>
                        <div class="col-md-6 text-right">
                            Total GPA: 4.0
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    {% for semester in semesters %}
                        <div class="row">
                            <div class="col-md-12">
                                <div class="panel panel-primary">
                                    <div class="panel-heading">
                                        <div class="row">
                                            <div class="col-md-6">
                                                Semester #{{forloop.counter}}
                                            </div>
                                            <div class="col-md-6 text-right">
                                                GPA: {{semester.GPA}}
                                            </div>
                                        </div>
                                    </div>
                                    <!-- <div class="panel-body"> -->
                                        <!-- ######################################### -->

                                        <ul class="list-group">
                                            {% for c_c in semester.completedcourse_set.all %}
                                                <li class="list-group-item">
                                                    <div class="row">
                                                        <div class="col-md-6">
                                                            <a href="{% url 'coursesApp:view_course' c_c.course.id %}" class="sessionCourse">#{{c_c.course.code}} - {{c_c.course.name}}</a><br>
                                                        </div>
                                                        <div class="col-md-2">
                                                            <b>Written: {{c_c.written_result}} / {{c_c.course.max_written_result}}</b>
                                                        </div>
                                                        <div class="col-md-2">
                                                            <b>Oral: {{c_c.oral_result}} / {{c_c.course.max_oral_result}}</b>
                                                        </div>
                                                        <div class="col-md-2">
                                                            <b>Applications: {{c_c.app_result}} / {{c_c.course.max_app_result}}</b>
                                                        </div>
                                                    </div>
                                                </li>
                                            {% endfor %}
                                        </ul>

                                        <!-- ######################################### -->
                                    <!-- </div> -->
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}